---
- name: Install packeges web
  yum:
   name: "{{ item }}"
   state: present
  loop:
   - httpd
   - firewalld

- name: Active services
  service:
   name: "{{ item }}"
   state: started
   enabled: true
  loop:
   - httpd
   - firewalld

- name: Active firewalld
  firewalld:
   service: http
   permanent: true
   state: enabled
   immediate: true

- name: Create content
  template:
   src: "{{ item }}"
   dest: "/var/www/html/{{ item }}"
  loop:
   - gaucho.svg.png
   - index

